### ISSUE TITLE
error with flank

### ISSUE THREAD

**Issue by crawld** [silvxlabs/DripTorch#114]
see attached notebook for reproducer. this is 0.7.1

[flank-tester.zip](https://github.com/silvxlabs/DripTorch/files/9789656/flank-tester.zip)

**Comment by frigusgulo** [comment]
Thanks for submitting! I ran your script and it looks like we have a dependency issue. I will let you know as soon as we figure out a solution.

**Comment by frigusgulo** [comment]
@lucaswells I think the issue stems from using conda to install awkward vs pip. My solution was to uninstall conda's Awkward and use pip, and then change that dependency in environment.yml:

`
pip:
- awkward=1.10.1

`

**Comment by lucaswells** [comment]
We were calling the `BurnUnit.bounds` property like this `bounds()` in the Flank pattern generator. This is fixed.
