### ISSUE TITLE
difference for strip side left or right?

### ISSUE THREAD

**Issue by crawld** [silvxlabs/DripTorch#115]
i'm not seeing a difference if side is left or right for strip.

**Comment by lucaswells** [comment]
@crawld, the `side` parameter controls which side of the wind direction the ignition crew starts. In the following example, the wind direction is 235*:

`side = 'right'`
![image](https://user-images.githubusercontent.com/12506947/196224469-7cdd4243-2bbd-4a78-adf5-352b9459f6f1.png)

`side = 'left'`
![image](https://user-images.githubusercontent.com/12506947/196224576-f77f9ad7-cdad-426d-84da-d83fb4f587ff.png)
