### ISSUE TITLE
Feature request: Igniter Stagger /  Delay in Flanking Fire

### ISSUE THREAD

**Issue by drosales95** [silvxlabs/DripTorch#119]
Could we get an igniter time delay added for the flanking ignition pattern? 

I completely understand the concerns of having igniters walking into potentially dangerous situations but there are situations where the manager requests those timing delays and we would like to match those. Furthermore, we can imagine multiple drones doing so.

**Comment by frigusgulo** [comment]
@drosales95 Could you elaborate a bit more about this? Specifically where in the simulation would this delay take place (i.e. during a specific heat, over a specific spatial boundary, etc.) 
And just to be clear what do you mean by 
> " Furthermore, we can imagine multiple drones doing so." ?

**Comment by lucaswells** [comment]
@frigusgulo, we need to add a spacing parameter, as we have in the strip technique, to stagger the igniters.

**Comment by frigusgulo** [comment]
@lucaswells Just curious but is it common practice to stagger igniters when firing parallel with the wind?

**Comment by lucaswells** [comment]
No, not to my knowledge. But it sounds like managers are requesting that functionality.
