### ISSUE TITLE
Fix 1.8m/s default velocity

### ISSUE THREAD

**Issue by lucaswells** [silvxlabs/DripTorch#97]
Convert 1.8 miles/hour to meters/second and replace default

**Comment by frigusgulo** [comment]
Yea 1.8 m/s is pretty GD fast.

**Comment by frigusgulo** [comment]
Might be good to add a "velocity" warning, ie let users know if theyre using physically improbably speeds

**Comment by lucaswells** [comment]
Usain Bolt can run about 10 m/s; half or even a quarter of that might be a good cap.
