### ISSUE TITLE
Time delay between heats

### ISSUE THREAD

**Issue by lucaswells** [silvxlabs/DripTorch#98]
Add a `heat_delay` argument for the flank and strip pattern generators to specify a delay in seconds between igniter heats.

**Comment by drosales95** [comment]
For the flank ignition, it would be good have it as an option to add it to the delay from walking around the unit or a flat delay. This could also be done by the user if there is a way to return the start time for each ignitor / heat, but I haven't dug around to find that.

**Comment by frigusgulo** [comment]
Thanks for the idea @drosales95, this certainly lends a bit more authenticity to the time aspect of these simulations.

**Comment by lucaswells** [comment]
@frigusgulo This issue didn't get merged. See PR #100.
